# Generated by Django 3.0.5 on 2020-05-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0002_auto_20200503_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candyimage',
            name='candy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy.Candy'),
        ),
    ]
